// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://xziropvhidyvginabopy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh6aXJvcHZoaWR5dmdpbmFib3B5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ1MDYyNjgsImV4cCI6MjA3MDA4MjI2OH0.GCu0YotorIN6GZktSsUbop2NyITUjc_A94KvxOhD944";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);